Fdsnws irisph5
obspy/obspy pull request #2739
Opened 2020-10-28 11:45 UTC by megies

### What does this PR do?

Adds support for IRISPH5 short URL mapping in FDSNWS Client. To make it work it would need some changes to internals unfortunately, since this FDSNWS is not following the FDSN specifications in that it does not have a `/fdsnws` subpath in between the base URL and the service endpoints.

Two possibilities to alleviate it:
 - change internals as done in this PR. implies that users should be able to navigate service versions using `major_versions` on Client init.
 - other option: set the full service URLS in `headers.py` and leave internals as is. less changes in code, but then users would not be able to use the `"IRISPH5"` URL mapping and use an (eventual) higher service major version. (not done in this PR)

This isn't really beautiful, so I'd like to hear some opinions on this.

### Why was it initiated?  Any relevant Issues?

closes #2737 

### PR Checklist
- [ ] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] If the PR is making changes to documentation, docs pages can be built automatically.
      Just remove the space in the following string after the + sign: "+ DOCS"
- [ ] If any network modules should be tested for the PR, add them as a comma separated list
      (e.g. `clients.fdsn,clients.arclink`) after the colon in the following magic string: "+TESTS:"
      (you can also add "ALL" to just simply run all tests across all modules)
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

2020-10-28 18:20 UTC, krischer requested changes
This looks fine to me and I think this works as expected.

One thing I think should be changed is to not have this data center as one of the default data centers in the mass downloader. It is fine if it can be optionally selected but this should be a conscious user choice as it could potentially download a truly massive amount of largely large-N or active source data which is not what most users of ObsPy would expect.

2020-10-29 07:55 UTC, megies commented
> It is fine if it can be optionally selected but this should be a conscious user choice as it could potentially download a truly massive amount of largely large-N or active source data which is not what most users of ObsPy would expect.

Yes, I agree. @jrekoske-usgs, you did explicitly mention using it for `MassDownloader`, but I think it should already help a lot having the short URL to go with in the mass downloader? Having it in there as a default could really lead to awkward scenarios for users.. we can mention it prominently in the docs for `MassDownloader`, I guess.

> This looks fine to me and I think this works as expected.

Yeah, I guess the code is already kinda convoluted anyway, so just the minor bit more complexity doesn't hurt too much

2020-10-29 08:53 UTC, krischer approved these changes

2020-10-29 08:53 UTC, krischer commented on obspy/clients/fdsn/mass_downloader/mass_downloader.py
> +        IRISPH5, you must set this parameter to
I forgot that RASPISHAKE is also already excluded - but definitely a sane default to exclude the raspian and irisph5 one!

2020-10-29 08:56 UTC, merged

2020-10-29 16:51 UTC, jrekoske-usgs commented
@megies This looks great, I agree that it makes sense to leave IRISPH5 out of the MassDownloader by default. Thanks for getting to this so quickly!